# Generated by Django 4.0.5 on 2023-04-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
